language: node_js
node_js:
 - 0.6
 - 0.8

branches:
 only:
  - Unstable
  - master
  - Issue#63

services:
 - mongodb
 - redis-server

install:
 - npm install

before_script:
 - node src/listener.js 2> /dev/null &
 - node src/consumer.js 2> /dev/null &