language: node_js

node_js:
 - "0.8"
 - "0.10"

branches:
  only:
    - unstable
    - master

services:
 - mongodb
 - redis-server

install:
 - npm install

before_script:
 - node lib/listener.js &
 - node lib/consumer.js &
